import asyncio
import pytest

from app.market_data.simulator import SimulatorSource, DEFAULT_TICKERS
from app.market_data.cache import PriceCache
from app.market_data.models import TickerConfig


@pytest.mark.asyncio
async def test_simulator_seeds_initial_prices():
    """After start(), all default tickers should have prices in the cache."""
    cache = PriceCache()
    source = SimulatorSource()
    await source.start(cache)

    for cfg in DEFAULT_TICKERS:
        tick = await cache.get_latest(cfg.ticker)
        assert tick is not None
        assert tick.price == cfg.seed_price

    await source.stop()


@pytest.mark.asyncio
async def test_simulator_prices_change_over_time():
    """After running for a bit, prices should remain positive."""
    cache = PriceCache()
    source = SimulatorSource()
    await source.start(cache)

    await asyncio.sleep(1.5)  # ~3 ticks

    for cfg in DEFAULT_TICKERS:
        tick = await cache.get_latest(cfg.ticker)
        assert tick is not None
        assert tick.price > 0

    await source.stop()


@pytest.mark.asyncio
async def test_simulator_all_tickers_tracked():
    """Default simulator tracks all 10 default tickers."""
    source = SimulatorSource()
    tracked = source.get_tracked_tickers()
    assert len(tracked) == len(DEFAULT_TICKERS)
    for cfg in DEFAULT_TICKERS:
        assert cfg.ticker in tracked


@pytest.mark.asyncio
async def test_add_ticker_dynamically():
    """Adding a ticker mid-simulation should seed it in the cache."""
    cache = PriceCache()
    source = SimulatorSource()
    await source.start(cache)

    source.add_ticker("PYPL")
    await asyncio.sleep(0.1)  # let the create_task complete

    tick = await cache.get_latest("PYPL")
    assert tick is not None
    assert tick.price > 0
    assert "PYPL" in source.get_tracked_tickers()

    await source.stop()


@pytest.mark.asyncio
async def test_add_ticker_idempotent():
    """Adding a ticker that already exists should not change its price."""
    cache = PriceCache()
    source = SimulatorSource()
    await source.start(cache)

    tick_before = await cache.get_latest("AAPL")
    initial_price = tick_before.price

    # Add AAPL again — should be ignored
    source.add_ticker("AAPL")
    await asyncio.sleep(0.1)

    tick_after = await cache.get_latest("AAPL")
    # The price may have changed due to simulation, but the seed price should not have reset
    assert tick_after is not None

    await source.stop()


@pytest.mark.asyncio
async def test_remove_ticker():
    """Removing a ticker should clear it from the source and cache."""
    cache = PriceCache()
    source = SimulatorSource()
    await source.start(cache)

    source.remove_ticker("AAPL")
    await asyncio.sleep(0.1)

    assert "AAPL" not in source.get_tracked_tickers()
    tick = await cache.get_latest("AAPL")
    assert tick is None

    await source.stop()


@pytest.mark.asyncio
async def test_remove_nonexistent_ticker_is_safe():
    """Removing a ticker that isn't tracked should not raise."""
    source = SimulatorSource()
    source.remove_ticker("NONEXISTENT")  # should not raise


@pytest.mark.asyncio
async def test_custom_tickers():
    """SimulatorSource can be initialized with a custom ticker list."""
    custom_tickers = [
        TickerConfig(ticker="CUSTOM1", seed_price=100.0),
        TickerConfig(ticker="CUSTOM2", seed_price=200.0),
    ]
    cache = PriceCache()
    source = SimulatorSource(tickers=custom_tickers)
    await source.start(cache)

    tick1 = await cache.get_latest("CUSTOM1")
    tick2 = await cache.get_latest("CUSTOM2")

    assert tick1 is not None
    assert tick2 is not None
    assert tick1.price == 100.0
    assert tick2.price == 200.0

    await source.stop()


@pytest.mark.asyncio
async def test_stop_prevents_further_updates():
    """After stop(), no new price updates should occur."""
    cache = PriceCache()
    source = SimulatorSource()
    await source.start(cache)

    await asyncio.sleep(0.6)  # let at least one tick happen
    await source.stop()

    version_after_stop = cache.version
    await asyncio.sleep(1.0)  # wait for what would have been more ticks

    # Version should not have changed after stop
    assert cache.version == version_after_stop


@pytest.mark.asyncio
async def test_gbm_prices_stay_positive():
    """Prices generated by GBM should never go negative or zero."""
    cache = PriceCache()
    source = SimulatorSource()
    await source.start(cache)

    await asyncio.sleep(2.0)  # ~4 ticks

    for ticker in source.get_tracked_tickers():
        tick = await cache.get_latest(ticker)
        assert tick is not None
        assert tick.price > 0

    await source.stop()


@pytest.mark.asyncio
async def test_history_populated_after_ticks():
    """Price history should be populated after the simulator runs."""
    cache = PriceCache()
    source = SimulatorSource()
    await source.start(cache)

    await asyncio.sleep(1.5)  # ~3 ticks

    history = await cache.get_history("AAPL")
    assert history is not None
    # Should have seed price + at least 2 more ticks
    assert len(history.prices) >= 3

    await source.stop()
